-- prerequisite: root access

CREATE DATABASE service;

-- password in 1pass
CREATE USER 'nextop_service'@'localhost' IDENTIFIED BY PASSWORD '*3D9BCD224C8613ADCBBE9E5CCC6053DEC7673165';
CREATE USER 'nextop_service'@'%' IDENTIFIED BY PASSWORD '*3D9BCD224C8613ADCBBE9E5CCC6053DEC7673165';
GRANT DELETE, SELECT, UPDATE, LOCK TABLES ON service.* TO 'nextop_service'@'localhost';
GRANT DELETE, SELECT, UPDATE, LOCK TABLES ON service.* TO 'nextop_service'@'%';
